apiVersion: v2
name: ethereum-reth-lighthouse
description: >
  Ethereum node with reth and lighthouse
home: https://soneium.com
sources:
  - https://github.com/soneium
type: application
version: 0.0.71
maintainers:
  - name: Sony
